# Site
name: "Women Who Care"
title: "Women Who Care"
description: "Offical blog for Women Who Care"
logo: 'assets/images/wwc_black.png'
favicon: '/assets/images/wwc_black.png'
baseurl: "/WomenWhoCare"
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/
email: wowthemesnet@gmail.com
url: https://soumyaa01.github.io

# Authors
authors:
  DeathWish:
    name: DeathWish
    display_name: DeathWish
    avatar: 'assets/images/avatar-deathwish.png'
    email: womenwhocare.in@gmail.com
    web: www.reddit.com/r/WomenWhoCare
    description: "Founder/owner WomenWhoCare"
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    instagram: https://twitter.com/wowthemesnet
    description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
